PUT http://localhost:3001/api/blogs/64e9ad807b8431e3cdbcd6a5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTk4OTcyMjcxM2IwZDZlNDc2OWI4NiIsInVzZXJuYW1lIjoiQm9kb3F1ZSIsImlhdCI6MTY5MzAzMjI3OSwiZXhwIjoxNjkzNjM3MDc5fQ.VyHmJoIEUs023iV5a7irgrHeGUDyWZtaVxthHvfHB0M

{
    "likes": 100
}

### invalid
PUT http://localhost:3003/api/blogs/64e99f8357ee8cb5bbb4fa8b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZTlhODIzNzQ0ZDQ0OTg0ZjJhZDQ3NyIsInVzZXJuYW1lIjoiQmVuaXRvIiwiaWF0IjoxNjkzMDM0NTk5LCJleHAiOjE2OTM2MzkzOTl9.27CZXYoDZecSj2PQJasuBe-yAd_iiV_9xgxig6DRAww

{
    "likes": 200
}

